filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/logs/*.log
    multiline.pattern: ^\{
    multiline.negate: true
    multiline.match: after

processors:
 - decode_json_fields:
     fields: ["message"]
     target: json

output.elasticsearch:
  enabled: true
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: changeme

logging.to_files: true

## X-Pack security credentials
#
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: changeme
